--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- collection_figures_alive class
local collection_figures_alive = {}
local collection_figures_alive_mt = {
	__name = "collection_figures_alive";
	__index = collection_figures_alive;
}

local function cast_collection_figures_alive(t)
	return setmetatable(t, collection_figures_alive_mt)
end

local function new_collection_figures_alive(count, size)
	return cast_collection_figures_alive({
		["count"] = count;
		["size"] = size;
	})
end

return {
	cast = cast_collection_figures_alive;
	new = new_collection_figures_alive;
}
