--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- collection_figures_compactors class
local collection_figures_compactors = {}
local collection_figures_compactors_mt = {
	__name = "collection_figures_compactors";
	__index = collection_figures_compactors;
}

local function cast_collection_figures_compactors(t)
	return setmetatable(t, collection_figures_compactors_mt)
end

local function new_collection_figures_compactors(count, file_size)
	return cast_collection_figures_compactors({
		["count"] = count;
		["fileSize"] = file_size;
	})
end

return {
	cast = cast_collection_figures_compactors;
	new = new_collection_figures_compactors;
}
