--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- collection_figures_indexes class
local collection_figures_indexes = {}
local collection_figures_indexes_mt = {
	__name = "collection_figures_indexes";
	__index = collection_figures_indexes;
}

local function cast_collection_figures_indexes(t)
	return setmetatable(t, collection_figures_indexes_mt)
end

local function new_collection_figures_indexes(count, size)
	return cast_collection_figures_indexes({
		["count"] = count;
		["size"] = size;
	})
end

return {
	cast = cast_collection_figures_indexes;
	new = new_collection_figures_indexes;
}
