--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- collection_figures_datafiles class
local collection_figures_datafiles = {}
local collection_figures_datafiles_mt = {
	__name = "collection_figures_datafiles";
	__index = collection_figures_datafiles;
}

local function cast_collection_figures_datafiles(t)
	return setmetatable(t, collection_figures_datafiles_mt)
end

local function new_collection_figures_datafiles(count, file_size)
	return cast_collection_figures_datafiles({
		["count"] = count;
		["fileSize"] = file_size;
	})
end

return {
	cast = cast_collection_figures_datafiles;
	new = new_collection_figures_datafiles;
}
