--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- collection_figures_dead class
local collection_figures_dead = {}
local collection_figures_dead_mt = {
	__name = "collection_figures_dead";
	__index = collection_figures_dead;
}

local function cast_collection_figures_dead(t)
	return setmetatable(t, collection_figures_dead_mt)
end

local function new_collection_figures_dead(count, deletion, size)
	return cast_collection_figures_dead({
		["count"] = count;
		["deletion"] = deletion;
		["size"] = size;
	})
end

return {
	cast = cast_collection_figures_dead;
	new = new_collection_figures_dead;
}
