--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- collection_figures_journals class
local collection_figures_journals = {}
local collection_figures_journals_mt = {
	__name = "collection_figures_journals";
	__index = collection_figures_journals;
}

local function cast_collection_figures_journals(t)
	return setmetatable(t, collection_figures_journals_mt)
end

local function new_collection_figures_journals(count, file_size)
	return cast_collection_figures_journals({
		["count"] = count;
		["fileSize"] = file_size;
	})
end

return {
	cast = cast_collection_figures_journals;
	new = new_collection_figures_journals;
}
