--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- collection_figures_readcache class
local collection_figures_readcache = {}
local collection_figures_readcache_mt = {
	__name = "collection_figures_readcache";
	__index = collection_figures_readcache;
}

local function cast_collection_figures_readcache(t)
	return setmetatable(t, collection_figures_readcache_mt)
end

local function new_collection_figures_readcache(count, size)
	return cast_collection_figures_readcache({
		["count"] = count;
		["size"] = size;
	})
end

return {
	cast = cast_collection_figures_readcache;
	new = new_collection_figures_readcache;
}
