--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- collection_figures class
local collection_figures = {}
local collection_figures_mt = {
	__name = "collection_figures";
	__index = collection_figures;
}

local function cast_collection_figures(t)
	return setmetatable(t, collection_figures_mt)
end

local function new_collection_figures(alive, compaction_status, compactors, datafiles, dead, document_references, indexes, journals, last_tick, readcache, revisions, uncollected_logfile_entries, waiting_for)
	return cast_collection_figures({
		["alive"] = alive;
		["compactionStatus"] = compaction_status;
		["compactors"] = compactors;
		["datafiles"] = datafiles;
		["dead"] = dead;
		["documentReferences"] = document_references;
		["indexes"] = indexes;
		["journals"] = journals;
		["lastTick"] = last_tick;
		["readcache"] = readcache;
		["revisions"] = revisions;
		["uncollectedLogfileEntries"] = uncollected_logfile_entries;
		["waitingFor"] = waiting_for;
	})
end

return {
	cast = cast_collection_figures;
	new = new_collection_figures;
}
