--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- collection_figures_revisions class
local collection_figures_revisions = {}
local collection_figures_revisions_mt = {
	__name = "collection_figures_revisions";
	__index = collection_figures_revisions;
}

local function cast_collection_figures_revisions(t)
	return setmetatable(t, collection_figures_revisions_mt)
end

local function new_collection_figures_revisions(count, size)
	return cast_collection_figures_revisions({
		["count"] = count;
		["size"] = size;
	})
end

return {
	cast = cast_collection_figures_revisions;
	new = new_collection_figures_revisions;
}
