--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- compaction_status_attributes class
local compaction_status_attributes = {}
local compaction_status_attributes_mt = {
	__name = "compaction_status_attributes";
	__index = compaction_status_attributes;
}

local function cast_compaction_status_attributes(t)
	return setmetatable(t, compaction_status_attributes_mt)
end

local function new_compaction_status_attributes(message, time)
	return cast_compaction_status_attributes({
		["message"] = message;
		["time"] = time;
	})
end

return {
	cast = cast_compaction_status_attributes;
	new = new_compaction_status_attributes;
}
