--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsa_put_api_simple_first_example class
local jsa_put_api_simple_first_example = {}
local jsa_put_api_simple_first_example_mt = {
	__name = "jsa_put_api_simple_first_example";
	__index = jsa_put_api_simple_first_example;
}

local function cast_jsa_put_api_simple_first_example(t)
	return setmetatable(t, jsa_put_api_simple_first_example_mt)
end

local function new_jsa_put_api_simple_first_example(collection, example)
	return cast_jsa_put_api_simple_first_example({
		["collection"] = collection;
		["example"] = example;
	})
end

return {
	cast = cast_jsa_put_api_simple_first_example;
	new = new_jsa_put_api_simple_first_example;
}
