--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsa_put_api_simple_fulltext class
local jsa_put_api_simple_fulltext = {}
local jsa_put_api_simple_fulltext_mt = {
	__name = "jsa_put_api_simple_fulltext";
	__index = jsa_put_api_simple_fulltext;
}

local function cast_jsa_put_api_simple_fulltext(t)
	return setmetatable(t, jsa_put_api_simple_fulltext_mt)
end

local function new_jsa_put_api_simple_fulltext(attribute, collection, index, limit, query, skip)
	return cast_jsa_put_api_simple_fulltext({
		["attribute"] = attribute;
		["collection"] = collection;
		["index"] = index;
		["limit"] = limit;
		["query"] = query;
		["skip"] = skip;
	})
end

return {
	cast = cast_jsa_put_api_simple_fulltext;
	new = new_jsa_put_api_simple_fulltext;
}
