--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsa_get_api_collection_figures_rc_200 class
local jsa_get_api_collection_figures_rc_200 = {}
local jsa_get_api_collection_figures_rc_200_mt = {
	__name = "jsa_get_api_collection_figures_rc_200";
	__index = jsa_get_api_collection_figures_rc_200;
}

local function cast_jsa_get_api_collection_figures_rc_200(t)
	return setmetatable(t, jsa_get_api_collection_figures_rc_200_mt)
end

local function new_jsa_get_api_collection_figures_rc_200(count, figures, journal_size)
	return cast_jsa_get_api_collection_figures_rc_200({
		["count"] = count;
		["figures"] = figures;
		["journalSize"] = journal_size;
	})
end

return {
	cast = cast_jsa_get_api_collection_figures_rc_200;
	new = new_jsa_get_api_collection_figures_rc_200;
}
