--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsa_put_api_simple_within class
local jsa_put_api_simple_within = {}
local jsa_put_api_simple_within_mt = {
	__name = "jsa_put_api_simple_within";
	__index = jsa_put_api_simple_within;
}

local function cast_jsa_put_api_simple_within(t)
	return setmetatable(t, jsa_put_api_simple_within_mt)
end

local function new_jsa_put_api_simple_within(collection, distance, geo, latitude, limit, longitude, radius, skip)
	return cast_jsa_put_api_simple_within({
		["collection"] = collection;
		["distance"] = distance;
		["geo"] = geo;
		["latitude"] = latitude;
		["limit"] = limit;
		["longitude"] = longitude;
		["radius"] = radius;
		["skip"] = skip;
	})
end

return {
	cast = cast_jsa_put_api_simple_within;
	new = new_jsa_put_api_simple_within;
}
