--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsa_put_api_simple_range class
local jsa_put_api_simple_range = {}
local jsa_put_api_simple_range_mt = {
	__name = "jsa_put_api_simple_range";
	__index = jsa_put_api_simple_range;
}

local function cast_jsa_put_api_simple_range(t)
	return setmetatable(t, jsa_put_api_simple_range_mt)
end

local function new_jsa_put_api_simple_range(attribute, closed, collection, left, limit, right, skip)
	return cast_jsa_put_api_simple_range({
		["attribute"] = attribute;
		["closed"] = closed;
		["collection"] = collection;
		["left"] = left;
		["limit"] = limit;
		["right"] = right;
		["skip"] = skip;
	})
end

return {
	cast = cast_jsa_put_api_simple_range;
	new = new_jsa_put_api_simple_range;
}
