--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsa_put_api_simple_within_rectangle class
local jsa_put_api_simple_within_rectangle = {}
local jsa_put_api_simple_within_rectangle_mt = {
	__name = "jsa_put_api_simple_within_rectangle";
	__index = jsa_put_api_simple_within_rectangle;
}

local function cast_jsa_put_api_simple_within_rectangle(t)
	return setmetatable(t, jsa_put_api_simple_within_rectangle_mt)
end

local function new_jsa_put_api_simple_within_rectangle(collection, geo, latitude1, latitude2, limit, longitude1, longitude2, skip)
	return cast_jsa_put_api_simple_within_rectangle({
		["collection"] = collection;
		["geo"] = geo;
		["latitude1"] = latitude1;
		["latitude2"] = latitude2;
		["limit"] = limit;
		["longitude1"] = longitude1;
		["longitude2"] = longitude2;
		["skip"] = skip;
	})
end

return {
	cast = cast_jsa_put_api_simple_within_rectangle;
	new = new_jsa_put_api_simple_within_rectangle;
}
