--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsa_put_api_simple_near class
local jsa_put_api_simple_near = {}
local jsa_put_api_simple_near_mt = {
	__name = "jsa_put_api_simple_near";
	__index = jsa_put_api_simple_near;
}

local function cast_jsa_put_api_simple_near(t)
	return setmetatable(t, jsa_put_api_simple_near_mt)
end

local function new_jsa_put_api_simple_near(collection, distance, geo, latitude, limit, longitude, skip)
	return cast_jsa_put_api_simple_near({
		["collection"] = collection;
		["distance"] = distance;
		["geo"] = geo;
		["latitude"] = latitude;
		["limit"] = limit;
		["longitude"] = longitude;
		["skip"] = skip;
	})
end

return {
	cast = cast_jsa_put_api_simple_near;
	new = new_jsa_put_api_simple_near;
}
