--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_export_restrictions class
local jsf_post_api_export_restrictions = {}
local jsf_post_api_export_restrictions_mt = {
	__name = "jsf_post_api_export_restrictions";
	__index = jsf_post_api_export_restrictions;
}

local function cast_jsf_post_api_export_restrictions(t)
	return setmetatable(t, jsf_post_api_export_restrictions_mt)
end

local function new_jsf_post_api_export_restrictions(fields, type)
	return cast_jsf_post_api_export_restrictions({
		["fields"] = fields;
		["type"] = type;
	})
end

return {
	cast = cast_jsf_post_api_export_restrictions;
	new = new_jsf_post_api_export_restrictions;
}
