--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_aqlfunction class
local jsf_post_api_aqlfunction = {}
local jsf_post_api_aqlfunction_mt = {
	__name = "jsf_post_api_aqlfunction";
	__index = jsf_post_api_aqlfunction;
}

local function cast_jsf_post_api_aqlfunction(t)
	return setmetatable(t, jsf_post_api_aqlfunction_mt)
end

local function new_jsf_post_api_aqlfunction(code, is_deterministic, name)
	return cast_jsf_post_api_aqlfunction({
		["code"] = code;
		["isDeterministic"] = is_deterministic;
		["name"] = name;
	})
end

return {
	cast = cast_jsf_post_api_aqlfunction;
	new = new_jsf_post_api_aqlfunction;
}
