--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_get_api_database_new class
local jsf_get_api_database_new = {}
local jsf_get_api_database_new_mt = {
	__name = "jsf_get_api_database_new";
	__index = jsf_get_api_database_new;
}

local function cast_jsf_get_api_database_new(t)
	return setmetatable(t, jsf_get_api_database_new_mt)
end

local function new_jsf_get_api_database_new(name, users)
	return cast_jsf_get_api_database_new({
		["name"] = name;
		["users"] = users;
	})
end

return {
	cast = cast_jsf_get_api_database_new;
	new = new_jsf_get_api_database_new;
}
