--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_cursor_rc_400 class
local jsf_post_api_cursor_rc_400 = {}
local jsf_post_api_cursor_rc_400_mt = {
	__name = "jsf_post_api_cursor_rc_400";
	__index = jsf_post_api_cursor_rc_400;
}

local function cast_jsf_post_api_cursor_rc_400(t)
	return setmetatable(t, jsf_post_api_cursor_rc_400_mt)
end

local function new_jsf_post_api_cursor_rc_400(code, error, error_message, error_num)
	return cast_jsf_post_api_cursor_rc_400({
		["code"] = code;
		["error"] = error;
		["errorMessage"] = error_message;
		["errorNum"] = error_num;
	})
end

return {
	cast = cast_jsf_post_api_cursor_rc_400;
	new = new_jsf_post_api_cursor_rc_400;
}
