--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_http_api_traversal class
local jsf_http_api_traversal = {}
local jsf_http_api_traversal_mt = {
	__name = "jsf_http_api_traversal";
	__index = jsf_http_api_traversal;
}

local function cast_jsf_http_api_traversal(t)
	return setmetatable(t, jsf_http_api_traversal_mt)
end

local function new_jsf_http_api_traversal(direction, edge_collection, expander, filter, graph_name, init, item_order, max_depth, max_iterations, min_depth, order, sort, start_vertex, strategy, uniqueness, visitor)
	return cast_jsf_http_api_traversal({
		["direction"] = direction;
		["edgeCollection"] = edge_collection;
		["expander"] = expander;
		["filter"] = filter;
		["graphName"] = graph_name;
		["init"] = init;
		["itemOrder"] = item_order;
		["maxDepth"] = max_depth;
		["maxIterations"] = max_iterations;
		["minDepth"] = min_depth;
		["order"] = order;
		["sort"] = sort;
		["startVertex"] = start_vertex;
		["strategy"] = strategy;
		["uniqueness"] = uniqueness;
		["visitor"] = visitor;
	})
end

return {
	cast = cast_jsf_http_api_traversal;
	new = new_jsf_http_api_traversal;
}
