--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_database_open_auth class
local jsf_post_api_database_open_auth = {}
local jsf_post_api_database_open_auth_mt = {
	__name = "jsf_post_api_database_open_auth";
	__index = jsf_post_api_database_open_auth;
}

local function cast_jsf_post_api_database_open_auth(t)
	return setmetatable(t, jsf_post_api_database_open_auth_mt)
end

local function new_jsf_post_api_database_open_auth(username, password)
	return cast_jsf_post_api_database_open_auth({
		["username"] = username;
		["password"] = password;
	})
end

return {
	cast = cast_jsf_post_api_database_open_auth;
	new = new_jsf_post_api_database_open_auth;
}
