--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_put_api_replication_applier_adjust class
local jsf_put_api_replication_applier_adjust = {}
local jsf_put_api_replication_applier_adjust_mt = {
	__name = "jsf_put_api_replication_applier_adjust";
	__index = jsf_put_api_replication_applier_adjust;
}

local function cast_jsf_put_api_replication_applier_adjust(t)
	return setmetatable(t, jsf_put_api_replication_applier_adjust_mt)
end

local function new_jsf_put_api_replication_applier_adjust(adaptive_polling, auto_resync, auto_resync_retries, auto_start, chunk_size, connect_timeout, connection_retry_wait_time, database, endpoint, idle_max_wait_time, idle_min_wait_time, include_system, initial_sync_max_wait_time, max_connect_retries, password, request_timeout, require_from_present, restrict_collections, restrict_type, username, verbose)
	return cast_jsf_put_api_replication_applier_adjust({
		["adaptivePolling"] = adaptive_polling;
		["autoResync"] = auto_resync;
		["autoResyncRetries"] = auto_resync_retries;
		["autoStart"] = auto_start;
		["chunkSize"] = chunk_size;
		["connectTimeout"] = connect_timeout;
		["connectionRetryWaitTime"] = connection_retry_wait_time;
		["database"] = database;
		["endpoint"] = endpoint;
		["idleMaxWaitTime"] = idle_max_wait_time;
		["idleMinWaitTime"] = idle_min_wait_time;
		["includeSystem"] = include_system;
		["initialSyncMaxWaitTime"] = initial_sync_max_wait_time;
		["maxConnectRetries"] = max_connect_retries;
		["password"] = password;
		["requestTimeout"] = request_timeout;
		["requireFromPresent"] = require_from_present;
		["restrictCollections"] = restrict_collections;
		["restrictType"] = restrict_type;
		["username"] = username;
		["verbose"] = verbose;
	})
end

return {
	cast = cast_jsf_put_api_replication_applier_adjust;
	new = new_jsf_put_api_replication_applier_adjust;
}
