--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_collection_opts class
local jsf_post_api_collection_opts = {}
local jsf_post_api_collection_opts_mt = {
	__name = "jsf_post_api_collection_opts";
	__index = jsf_post_api_collection_opts;
}

local function cast_jsf_post_api_collection_opts(t)
	return setmetatable(t, jsf_post_api_collection_opts_mt)
end

local function new_jsf_post_api_collection_opts(allow_user_keys, increment, offset, type)
	return cast_jsf_post_api_collection_opts({
		["allowUserKeys"] = allow_user_keys;
		["increment"] = increment;
		["offset"] = offset;
		["type"] = type;
	})
end

return {
	cast = cast_jsf_post_api_collection_opts;
	new = new_jsf_post_api_collection_opts;
}
