--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_general_graph_edge_definition_add_http_examples class
local jsf_general_graph_edge_definition_add_http_examples = {}
local jsf_general_graph_edge_definition_add_http_examples_mt = {
	__name = "jsf_general_graph_edge_definition_add_http_examples";
	__index = jsf_general_graph_edge_definition_add_http_examples;
}

local function cast_jsf_general_graph_edge_definition_add_http_examples(t)
	return setmetatable(t, jsf_general_graph_edge_definition_add_http_examples_mt)
end

local function new_jsf_general_graph_edge_definition_add_http_examples(collection, from, to)
	return cast_jsf_general_graph_edge_definition_add_http_examples({
		["collection"] = collection;
		["from"] = from;
		["to"] = to;
	})
end

return {
	cast = cast_jsf_general_graph_edge_definition_add_http_examples;
	new = new_jsf_general_graph_edge_definition_add_http_examples;
}
