--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_cursor_opts class
local jsf_post_api_cursor_opts = {}
local jsf_post_api_cursor_opts_mt = {
	__name = "jsf_post_api_cursor_opts";
	__index = jsf_post_api_cursor_opts;
}

local function cast_jsf_post_api_cursor_opts(t)
	return setmetatable(t, jsf_post_api_cursor_opts_mt)
end

local function new_jsf_post_api_cursor_opts(fail_on_warning, full_count, intermediate_commit_count, intermediate_commit_size, max_plans, max_transaction_size, max_warning_count, optimizer_rules, profile, satellite_sync_wait)
	return cast_jsf_post_api_cursor_opts({
		["failOnWarning"] = fail_on_warning;
		["fullCount"] = full_count;
		["intermediateCommitCount"] = intermediate_commit_count;
		["intermediateCommitSize"] = intermediate_commit_size;
		["maxPlans"] = max_plans;
		["maxTransactionSize"] = max_transaction_size;
		["maxWarningCount"] = max_warning_count;
		["optimizer.rules"] = optimizer_rules;
		["profile"] = profile;
		["satelliteSyncWait"] = satellite_sync_wait;
	})
end

return {
	cast = cast_jsf_post_api_cursor_opts;
	new = new_jsf_post_api_cursor_opts;
}
