--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_index_persistent class
local jsf_post_api_index_persistent = {}
local jsf_post_api_index_persistent_mt = {
	__name = "jsf_post_api_index_persistent";
	__index = jsf_post_api_index_persistent;
}

local function cast_jsf_post_api_index_persistent(t)
	return setmetatable(t, jsf_post_api_index_persistent_mt)
end

local function new_jsf_post_api_index_persistent(fields, sparse, type, unique)
	return cast_jsf_post_api_index_persistent({
		["fields"] = fields;
		["sparse"] = sparse;
		["type"] = type;
		["unique"] = unique;
	})
end

return {
	cast = cast_jsf_post_api_index_persistent;
	new = new_jsf_post_api_index_persistent;
}
