--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_export class
local jsf_post_api_export = {}
local jsf_post_api_export_mt = {
	__name = "jsf_post_api_export";
	__index = jsf_post_api_export;
}

local function cast_jsf_post_api_export(t)
	return setmetatable(t, jsf_post_api_export_mt)
end

local function new_jsf_post_api_export(batch_size, count, flush, flush_wait, limit, restrict, ttl)
	return cast_jsf_post_api_export({
		["batchSize"] = batch_size;
		["count"] = count;
		["flush"] = flush;
		["flushWait"] = flush_wait;
		["limit"] = limit;
		["restrict"] = restrict;
		["ttl"] = ttl;
	})
end

return {
	cast = cast_jsf_post_api_export;
	new = new_jsf_post_api_export;
}
