--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_cursor class
local jsf_post_api_cursor = {}
local jsf_post_api_cursor_mt = {
	__name = "jsf_post_api_cursor";
	__index = jsf_post_api_cursor;
}

local function cast_jsf_post_api_cursor(t)
	return setmetatable(t, jsf_post_api_cursor_mt)
end

local function new_jsf_post_api_cursor(batch_size, bind_vars, cache, count, memory_limit, options, query, ttl)
	return cast_jsf_post_api_cursor({
		["batchSize"] = batch_size;
		["bindVars"] = bind_vars;
		["cache"] = cache;
		["count"] = count;
		["memoryLimit"] = memory_limit;
		["options"] = options;
		["query"] = query;
		["ttl"] = ttl;
	})
end

return {
	cast = cast_jsf_post_api_cursor;
	new = new_jsf_post_api_cursor;
}
