--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_collection class
local jsf_post_api_collection = {}
local jsf_post_api_collection_mt = {
	__name = "jsf_post_api_collection";
	__index = jsf_post_api_collection;
}

local function cast_jsf_post_api_collection(t)
	return setmetatable(t, jsf_post_api_collection_mt)
end

local function new_jsf_post_api_collection(do_compact, index_buckets, is_system, is_volatile, journal_size, key_options, name, number_of_shards, replication_factor, shard_keys, type, wait_for_sync)
	return cast_jsf_post_api_collection({
		["doCompact"] = do_compact;
		["indexBuckets"] = index_buckets;
		["isSystem"] = is_system;
		["isVolatile"] = is_volatile;
		["journalSize"] = journal_size;
		["keyOptions"] = key_options;
		["name"] = name;
		["numberOfShards"] = number_of_shards;
		["replicationFactor"] = replication_factor;
		["shardKeys"] = shard_keys;
		["type"] = type;
		["waitForSync"] = wait_for_sync;
	})
end

return {
	cast = cast_jsf_post_api_collection;
	new = new_jsf_post_api_collection;
}
