--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_put_api_replication_synchronize class
local jsf_put_api_replication_synchronize = {}
local jsf_put_api_replication_synchronize_mt = {
	__name = "jsf_put_api_replication_synchronize";
	__index = jsf_put_api_replication_synchronize;
}

local function cast_jsf_put_api_replication_synchronize(t)
	return setmetatable(t, jsf_put_api_replication_synchronize_mt)
end

local function new_jsf_put_api_replication_synchronize(database, endpoint, include_system, incremental, initial_sync_max_wait_time, password, restrict_collections, restrict_type, username)
	return cast_jsf_put_api_replication_synchronize({
		["database"] = database;
		["endpoint"] = endpoint;
		["includeSystem"] = include_system;
		["incremental"] = incremental;
		["initialSyncMaxWaitTime"] = initial_sync_max_wait_time;
		["password"] = password;
		["restrictCollections"] = restrict_collections;
		["restrictType"] = restrict_type;
		["username"] = username;
	})
end

return {
	cast = cast_jsf_put_api_replication_synchronize;
	new = new_jsf_put_api_replication_synchronize;
}
