--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_index_skiplist class
local jsf_post_api_index_skiplist = {}
local jsf_post_api_index_skiplist_mt = {
	__name = "jsf_post_api_index_skiplist";
	__index = jsf_post_api_index_skiplist;
}

local function cast_jsf_post_api_index_skiplist(t)
	return setmetatable(t, jsf_post_api_index_skiplist_mt)
end

local function new_jsf_post_api_index_skiplist(deduplicate, fields, sparse, type, unique)
	return cast_jsf_post_api_index_skiplist({
		["deduplicate"] = deduplicate;
		["fields"] = fields;
		["sparse"] = sparse;
		["type"] = type;
		["unique"] = unique;
	})
end

return {
	cast = cast_jsf_post_api_index_skiplist;
	new = new_jsf_post_api_index_skiplist;
}
