--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_explain class
local jsf_post_api_explain = {}
local jsf_post_api_explain_mt = {
	__name = "jsf_post_api_explain";
	__index = jsf_post_api_explain;
}

local function cast_jsf_post_api_explain(t)
	return setmetatable(t, jsf_post_api_explain_mt)
end

local function new_jsf_post_api_explain(bind_vars, options, query)
	return cast_jsf_post_api_explain({
		["bindVars"] = bind_vars;
		["options"] = options;
		["query"] = query;
	})
end

return {
	cast = cast_jsf_post_api_explain;
	new = new_jsf_post_api_explain;
}
