--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_index_fulltext class
local jsf_post_api_index_fulltext = {}
local jsf_post_api_index_fulltext_mt = {
	__name = "jsf_post_api_index_fulltext";
	__index = jsf_post_api_index_fulltext;
}

local function cast_jsf_post_api_index_fulltext(t)
	return setmetatable(t, jsf_post_api_index_fulltext_mt)
end

local function new_jsf_post_api_index_fulltext(fields, min_length, type)
	return cast_jsf_post_api_index_fulltext({
		["fields"] = fields;
		["minLength"] = min_length;
		["type"] = type;
	})
end

return {
	cast = cast_jsf_post_api_index_fulltext;
	new = new_jsf_post_api_index_fulltext;
}
