--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_post_api_index_geo class
local jsf_post_api_index_geo = {}
local jsf_post_api_index_geo_mt = {
	__name = "jsf_post_api_index_geo";
	__index = jsf_post_api_index_geo;
}

local function cast_jsf_post_api_index_geo(t)
	return setmetatable(t, jsf_post_api_index_geo_mt)
end

local function new_jsf_post_api_index_geo(fields, geo_json, type)
	return cast_jsf_post_api_index_geo({
		["fields"] = fields;
		["geoJson"] = geo_json;
		["type"] = type;
	})
end

return {
	cast = cast_jsf_post_api_index_geo;
	new = new_jsf_post_api_index_geo;
}
