--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_get_api_database_new_users class
local jsf_get_api_database_new_users = {}
local jsf_get_api_database_new_users_mt = {
	__name = "jsf_get_api_database_new_users";
	__index = jsf_get_api_database_new_users;
}

local function cast_jsf_get_api_database_new_users(t)
	return setmetatable(t, jsf_get_api_database_new_users_mt)
end

local function new_jsf_get_api_database_new_users(active, extra, passwd, username)
	return cast_jsf_get_api_database_new_users({
		["active"] = active;
		["extra"] = extra;
		["passwd"] = passwd;
		["username"] = username;
	})
end

return {
	cast = cast_jsf_get_api_database_new_users;
	new = new_jsf_get_api_database_new_users;
}
