--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- jsf_get_api_return_rc_200 class
local jsf_get_api_return_rc_200 = {}
local jsf_get_api_return_rc_200_mt = {
	__name = "jsf_get_api_return_rc_200";
	__index = jsf_get_api_return_rc_200;
}

local function cast_jsf_get_api_return_rc_200(t)
	return setmetatable(t, jsf_get_api_return_rc_200_mt)
end

local function new_jsf_get_api_return_rc_200(details, server, version)
	return cast_jsf_get_api_return_rc_200({
		["details"] = details;
		["server"] = server;
		["version"] = version;
	})
end

return {
	cast = cast_jsf_get_api_return_rc_200;
	new = new_jsf_get_api_return_rc_200;
}
