--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- post_api_gharial_create_opts class
local post_api_gharial_create_opts = {}
local post_api_gharial_create_opts_mt = {
	__name = "post_api_gharial_create_opts";
	__index = post_api_gharial_create_opts;
}

local function cast_post_api_gharial_create_opts(t)
	return setmetatable(t, post_api_gharial_create_opts_mt)
end

local function new_post_api_gharial_create_opts(number_of_shards, replication_factor, smart_graph_attribute)
	return cast_post_api_gharial_create_opts({
		["numberOfShards"] = number_of_shards;
		["replicationFactor"] = replication_factor;
		["smartGraphAttribute"] = smart_graph_attribute;
	})
end

return {
	cast = cast_post_api_gharial_create_opts;
	new = new_post_api_gharial_create_opts;
}
