--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- post_api_query_properties class
local post_api_query_properties = {}
local post_api_query_properties_mt = {
	__name = "post_api_query_properties";
	__index = post_api_query_properties;
}

local function cast_post_api_query_properties(t)
	return setmetatable(t, post_api_query_properties_mt)
end

local function new_post_api_query_properties(query)
	return cast_post_api_query_properties({
		["query"] = query;
	})
end

return {
	cast = cast_post_api_query_properties;
	new = new_post_api_query_properties;
}
