--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- put_api_query_cache_properties class
local put_api_query_cache_properties = {}
local put_api_query_cache_properties_mt = {
	__name = "put_api_query_cache_properties";
	__index = put_api_query_cache_properties;
}

local function cast_put_api_query_cache_properties(t)
	return setmetatable(t, put_api_query_cache_properties_mt)
end

local function new_put_api_query_cache_properties(max_results, mode)
	return cast_put_api_query_cache_properties({
		["maxResults"] = max_results;
		["mode"] = mode;
	})
end

return {
	cast = cast_put_api_query_cache_properties;
	new = new_put_api_query_cache_properties;
}
