--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- put_api_simple_update_by_example_options class
local put_api_simple_update_by_example_options = {}
local put_api_simple_update_by_example_options_mt = {
	__name = "put_api_simple_update_by_example_options";
	__index = put_api_simple_update_by_example_options;
}

local function cast_put_api_simple_update_by_example_options(t)
	return setmetatable(t, put_api_simple_update_by_example_options_mt)
end

local function new_put_api_simple_update_by_example_options(keep_null, limit, merge_objects, wait_for_sync)
	return cast_put_api_simple_update_by_example_options({
		["keepNull"] = keep_null;
		["limit"] = limit;
		["mergeObjects"] = merge_objects;
		["waitForSync"] = wait_for_sync;
	})
end

return {
	cast = cast_put_api_simple_update_by_example_options;
	new = new_put_api_simple_update_by_example_options;
}
