--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- rest_remove_by_keys class
local rest_remove_by_keys = {}
local rest_remove_by_keys_mt = {
	__name = "rest_remove_by_keys";
	__index = rest_remove_by_keys;
}

local function cast_rest_remove_by_keys(t)
	return setmetatable(t, rest_remove_by_keys_mt)
end

local function new_rest_remove_by_keys(collection, keys, options)
	return cast_rest_remove_by_keys({
		["collection"] = collection;
		["keys"] = keys;
		["options"] = options;
	})
end

return {
	cast = cast_rest_remove_by_keys;
	new = new_rest_remove_by_keys;
}
