--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- rest_document_read_all class
local rest_document_read_all = {}
local rest_document_read_all_mt = {
	__name = "rest_document_read_all";
	__index = rest_document_read_all;
}

local function cast_rest_document_read_all(t)
	return setmetatable(t, rest_document_read_all_mt)
end

local function new_rest_document_read_all(collection, type)
	return cast_rest_document_read_all({
		["collection"] = collection;
		["type"] = type;
	})
end

return {
	cast = cast_rest_document_read_all;
	new = new_rest_document_read_all;
}
