--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- user_handling_create class
local user_handling_create = {}
local user_handling_create_mt = {
	__name = "user_handling_create";
	__index = user_handling_create;
}

local function cast_user_handling_create(t)
	return setmetatable(t, user_handling_create_mt)
end

local function new_user_handling_create(active, extra, passwd, user)
	return cast_user_handling_create({
		["active"] = active;
		["extra"] = extra;
		["passwd"] = passwd;
		["user"] = user;
	})
end

return {
	cast = cast_user_handling_create;
	new = new_user_handling_create;
}
