--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- user_handling_modify class
local user_handling_modify = {}
local user_handling_modify_mt = {
	__name = "user_handling_modify";
	__index = user_handling_modify;
}

local function cast_user_handling_modify(t)
	return setmetatable(t, user_handling_modify_mt)
end

local function new_user_handling_modify(active, extra, passwd)
	return cast_user_handling_modify({
		["active"] = active;
		["extra"] = extra;
		["passwd"] = passwd;
	})
end

return {
	cast = cast_user_handling_modify;
	new = new_user_handling_modify;
}
