--[[ 
  ArangoDB
 
  ArangoDB REST API Interface
 
  OpenAPI spec version: 1.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- user_handling_grant_collection class
local user_handling_grant_collection = {}
local user_handling_grant_collection_mt = {
	__name = "user_handling_grant_collection";
	__index = user_handling_grant_collection;
}

local function cast_user_handling_grant_collection(t)
	return setmetatable(t, user_handling_grant_collection_mt)
end

local function new_user_handling_grant_collection(grant)
	return cast_user_handling_grant_collection({
		["grant"] = grant;
	})
end

return {
	cast = cast_user_handling_grant_collection;
	new = new_user_handling_grant_collection;
}
